### ISSUE TITLE
setjmp

### ISSUE THREAD

**Issue by catesandrew** [bluesmoon/pngtocss#4]
replace setjmp.

I was getting an error: dereferencing pointer to incomplete type.
Googling I found that we should be using png_jmpbuf.

http://comments.gmane.org/gmane.comp.graphics.png.devel/4131

I replace line 337 with this and it compiled fine.
if (setjmp(png_jmpbuf(png_ptr))) {

**Comment by bluesmoon** [comment]
Well, this was fixed with commit 1037293f
